# Generated by Django 5.1.1 on 2024-09-11 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_alter_subjtest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjtest',
            name='subj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.subject', verbose_name='Дисциплина'),
        ),
    ]
