# Generated by Django 5.1.1 on 2024-11-29 21:12

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('imageURL', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на изображение')),
                ('text', models.TextField(default='', max_length=5048, verbose_name='Вопрос')),
                ('weight', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вес вопроса')),
                ('optionsNum', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество вариантов ответа')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Дисциплина')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='', max_length=5048, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение')),
                ('imageURL', models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на изображение')),
                ('isRight', models.BooleanField(blank=True, default=False, verbose_name='Верный ответ?')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.question', verbose_name='Вопрос')),
            ],
        ),
        migrations.CreateModel(
            name='SubjTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название теста')),
                ('questions_num', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Максимальное количество вопросов')),
                ('test_questions_num', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Вопросов в тесте')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.subject', verbose_name='Дисциплина')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.subjtest', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(default=datetime.datetime(2024, 11, 30, 0, 12, 35, 336465), verbose_name='Начало')),
                ('time_end', models.DateTimeField(default=datetime.datetime(2024, 11, 30, 0, 12, 35, 336465), verbose_name='Конец')),
                ('points', models.IntegerField(default=0, verbose_name='Баллы')),
                ('isFinished', models.BooleanField(default=False)),
                ('question_pool', models.JSONField(default=list, verbose_name='Пул вопросов')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.subjtest', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.BooleanField(default=False)),
                ('opt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.option', verbose_name='Вариант ответа')),
                ('quest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testApp.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.usertest', verbose_name='Тест')),
            ],
        ),
    ]
