# Generated by Django 5.1 on 2024-09-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Дисциплина'),
        ),
    ]
