# Generated by Django 5.1.1 on 2024-12-07 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_option_imageheight_option_imagewidth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='optionsNum',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(2)], verbose_name='Количество вариантов ответа'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(null=True, verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(null=True, verbose_name='Начало'),
        ),
    ]
