# Generated by Django 5.1 on 2024-09-11 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Дисциплина')),
                ('subj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testApp.subject')),
            ],
        ),
    ]
