# Generated by Django 5.1.1 on 2024-12-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_alter_question_optionsnum_alter_usertest_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default='', max_length=5048, verbose_name='Вопрос'),
        ),
    ]
