# Generated by Django 5.1 on 2024-09-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_subjtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjtest',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Название теста'),
        ),
    ]
