# Generated by Django 4.2.1 on 2024-09-26 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_question_weight_usertest_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertest',
            name='isFinished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 13, 42, 51, 815692), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 13, 42, 51, 815692), verbose_name='Начало'),
        ),
    ]
