# Generated by Django 4.2.1 on 2024-09-26 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0013_usertest_isfinished_alter_usertest_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='points',
            field=models.IntegerField(default=0, verbose_name='Баллы'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 13, 44, 5, 30364), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 13, 44, 5, 30364), verbose_name='Начало'),
        ),
    ]
