# Generated by Django 4.2.1 on 2024-09-26 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0014_alter_usertest_points_alter_usertest_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='quest',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='testApp.question', verbose_name='Вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 13, 50, 34, 576112), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 13, 50, 34, 576112), verbose_name='Начало'),
        ),
    ]
