# Generated by Django 4.2.1 on 2024-09-26 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0016_alter_useranswer_quest_alter_usertest_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 14, 1, 49, 977400), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 26, 14, 1, 49, 977400), verbose_name='Начало'),
        ),
    ]
