# Generated by Django 4.2.1 on 2024-10-24 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0019_alter_question_image_alter_usertest_time_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='isRight',
            field=models.BooleanField(blank=True, default=False, verbose_name='Верный ответ?'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 18, 48, 56, 805661), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 24, 18, 48, 56, 805661), verbose_name='Начало'),
        ),
    ]
