# Generated by Django 5.1 on 2024-11-12 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0028_question_imageurl_alter_usertest_time_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='imageURL',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_end',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 18, 0, 15, 54264), verbose_name='Конец'),
        ),
        migrations.AlterField(
            model_name='usertest',
            name='time_start',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 12, 18, 0, 15, 54264), verbose_name='Начало'),
        ),
    ]
